{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25ee9fda",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "96d13e6e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<AsyncResult(_push): pending>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dff933b3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61a3505d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "534a4f56",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "We have 22716 News videos to process.\n",
      "We have 404 Entertainment videos to process.\n",
      "We have 518 UK Show videos to process.\n",
      "We have 3200 US Show videos to process.\n",
      "In total, there are 26838 videos.\n",
      "Sample persons_found list: [{'url': 'https://youtu.be/LOA-rEMU8pA', 'persons_found': ['Ben Affleck', 'Margot Robbie', 'Ryan Gosling']}, {'url': 'https://youtu.be/t9H3_ewSKI8', 'persons_found': ['Chris Hemsworth', 'Hugh Jackman', 'Tom Cruise']}, {'url': 'https://youtu.be/rFnB7gTk8L8', 'persons_found': ['Nicole Kidman', 'Ryan Gosling']}]\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "News_videos = \"News_person_search_results.csv\"\n",
    "Entertainment_videos = \"Other_Entertainment_person_search_results.csv\"\n",
    "UK_Show_videos= \"UK_Shows_person_search_results.csv\"\n",
    "US_Show_videos=\"US_Shows_person_search_results.csv\"\n",
    "\n",
    "#list of urls\n",
    "\n",
    "News_urls_and_persons = []\n",
    "Entertainment_urls_and_persons = []\n",
    "UK_urls_and_persons = []\n",
    "US_urls_and_persons = []\n",
    "\n",
    "News_urls = []\n",
    "Entertainment_urls = []\n",
    "UK_urls = []\n",
    "US_urls = []\n",
    "def SaveFunction(file, url_list, urls_and_persons):\n",
    "    df = pd.read_csv(file, dtype = {\n",
    "        'video_id': str,\n",
    "        'url': str,\n",
    "        'title': str,\n",
    "        'channel_name': str,\n",
    "        'published_at': str,\n",
    "        'view_count': 'Int64',\n",
    "        'persons_found': str,\n",
    "        'total_persons': 'Int64'\n",
    "    })\n",
    "    df['persons_found_list'] = (df['persons_found'].fillna('')\n",
    "                     .apply(lambda x: [name.strip() for name in x.split(',') if name.strip()])\n",
    "                    )\n",
    "    for url, persons in zip(df['url'], df['persons_found_list']):\n",
    "        url_list.append(url)\n",
    "        record = {\n",
    "            \"url\": url,\n",
    "            \"persons_found\": persons\n",
    "        }\n",
    "        urls_and_persons.append(record)\n",
    "\n",
    "SaveFunction(News_videos, News_urls, News_urls_and_persons)\n",
    "SaveFunction(Entertainment_videos, Entertainment_urls, Entertainment_urls_and_persons)\n",
    "SaveFunction(UK_Show_videos, UK_urls, UK_urls_and_persons)\n",
    "SaveFunction(US_Show_videos, US_urls, US_urls_and_persons)\n",
    "\n",
    "print(f\"We have {len(News_urls)} News videos to process.\")\n",
    "print(f\"We have {len(Entertainment_urls)} Entertainment videos to process.\")\n",
    "print(f\"We have {len(UK_urls)} UK Show videos to process.\")\n",
    "print(f\"We have {len(US_urls)} US Show videos to process.\")\n",
    "print(f\"In total, there are {len(News_urls)+len(Entertainment_urls)+len(UK_urls)+ len(US_urls)} videos.\")\n",
    "print(f\"Sample persons_found list: {UK_urls_and_persons[:3]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80b4bbee",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9188a4e4",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-29 15:10:56 INFO     Resumed state: 1614 docs, 134 failures, 1748 done\n",
      "2025-05-29 15:10:59 INFO     ✅ [https://youtu.be/N-9z9_OX5vw] loaded on attempt 1\n",
      "2025-05-29 15:11:05 INFO     ✅ [https://youtu.be/JnvnBDUZX4g] loaded on attempt 1\n",
      "2025-05-29 15:11:10 ERROR    ❌ [https://youtu.be/VvKDjNkP0x8] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=VvKDjNkP0x8! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=VvKDjNkP0x8! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "2025-05-29 15:11:10 ERROR    ✖️  [https://youtu.be/VvKDjNkP0x8] failed after 3 attempts\n",
      "2025-05-29 15:11:16 INFO     ✅ [https://youtu.be/GX_IVnmoHUE] loaded on attempt 1\n",
      "2025-05-29 15:11:21 INFO     ✅ [https://youtu.be/hmZELn3IbNU] loaded on attempt 1\n",
      "2025-05-29 15:11:26 WARNING  ⚠️  [https://youtu.be/X9tDERFjOMw] parse error on attempt 1: no element found: line 1, column 0\n",
      "2025-05-29 15:11:31 INFO     ✅ [https://youtu.be/X9tDERFjOMw] loaded on attempt 2\n",
      "2025-05-29 15:11:36 ERROR    ❌ [https://youtu.be/ROBO6_v40MU] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ROBO6_v40MU! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ROBO6_v40MU! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-29 15:11:36 ERROR    ✖️  [https://youtu.be/ROBO6_v40MU] failed after 3 attempts\n",
      "2025-05-29 15:11:40 INFO     ✅ [https://youtu.be/NR-uhyZ0W2c] loaded on attempt 1\n",
      "2025-05-29 15:11:45 ERROR    ❌ [https://youtu.be/ZLcyBj-ZuIM] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ZLcyBj-ZuIM! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ZLcyBj-ZuIM! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "2025-05-29 15:11:45 ERROR    ✖️  [https://youtu.be/ZLcyBj-ZuIM] failed after 3 attempts\n",
      "2025-05-29 15:11:50 ERROR    ❌ [https://youtu.be/lzK3x3_5HVo] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=lzK3x3_5HVo! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=lzK3x3_5HVo! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-29 15:11:50 ERROR    ✖️  [https://youtu.be/lzK3x3_5HVo] failed after 3 attempts\n",
      "2025-05-29 15:11:55 INFO     ✅ [https://youtu.be/Nd2XvMTPWh4] loaded on attempt 1\n",
      "2025-05-29 15:12:00 ERROR    ❌ [https://youtu.be/mIyJttK8aq4] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=mIyJttK8aq4! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=mIyJttK8aq4! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "2025-05-29 15:12:00 ERROR    ✖️  [https://youtu.be/mIyJttK8aq4] failed after 3 attempts\n",
      "2025-05-29 15:12:05 ERROR    ❌ [https://youtu.be/_21pbizBR9Y] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=_21pbizBR9Y! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=_21pbizBR9Y! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-29 15:12:05 ERROR    ✖️  [https://youtu.be/_21pbizBR9Y] failed after 3 attempts\n",
      "2025-05-29 15:12:10 INFO     ✅ [https://youtu.be/Jr7y6tZ3IL4] loaded on attempt 1\n",
      "2025-05-29 15:12:16 ERROR    ❌ [https://youtu.be/-2DKPhdxv0s] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=-2DKPhdxv0s! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=-2DKPhdxv0s! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "2025-05-29 15:12:16 ERROR    ✖️  [https://youtu.be/-2DKPhdxv0s] failed after 3 attempts\n",
      "2025-05-29 15:12:21 ERROR    ❌ [https://youtu.be/iYGHrt1HjI8] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=iYGHrt1HjI8! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=iYGHrt1HjI8! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-29 15:12:21 ERROR    ✖️  [https://youtu.be/iYGHrt1HjI8] failed after 3 attempts\n",
      "2025-05-29 15:12:27 INFO     ✅ [https://youtu.be/NC5NZPrxbHk] loaded on attempt 1\n",
      "2025-05-29 15:12:32 WARNING  ⚠️  [https://youtu.be/pcuwZ8zk2ng] parse error on attempt 1: no element found: line 1, column 0\n",
      "2025-05-29 15:12:38 INFO     ✅ [https://youtu.be/pcuwZ8zk2ng] loaded on attempt 2\n",
      "2025-05-29 15:12:43 ERROR    ❌ [https://youtu.be/DcvdOWitb3I] unexpected error: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=DcvdOWitb3I! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_30964/3307234849.py\", line 56, in load_with_retry\n",
      "    ).load()\n",
      "      ~~~~^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py\", line 262, in load\n",
      "    transcript_list = YouTubeTranscriptApi.list_transcripts(self.video_id)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 207, in list_transcripts\n",
      "    return ytt_api.list(video_id)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py\", line 135, in list\n",
      "    return self._fetcher.fetch(video_id)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 352, in fetch\n",
      "    self._fetch_captions_json(video_id),\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 368, in _fetch_captions_json\n",
      "    raise exception.with_proxy_config(self._proxy_config)\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 357, in _fetch_captions_json\n",
      "    return self._extract_captions_json(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._fetch_video_html(video_id), video_id\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 380, in _extract_captions_json\n",
      "    self._assert_playability(video_data.get(\"playabilityStatus\"), video_id)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py\", line 399, in _assert_playability\n",
      "    raise RequestBlocked(video_id)\n",
      "youtube_transcript_api._errors.RequestBlocked: \n",
      "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=DcvdOWitb3I! This is most likely caused by:\n",
      "\n",
      "YouTube is blocking requests from your IP. This usually is due to one of the following reasons:\n",
      "- You have done too many requests and your IP has been blocked by YouTube\n",
      "- You are doing requests from an IP belonging to a cloud provider (like AWS, Google Cloud Platform, Azure, etc.). Unfortunately, most IPs from cloud providers are blocked by YouTube.\n",
      "\n",
      "There are two things you can do to work around this:\n",
      "1. Use proxies to hide your IP address, as explained in the \"Working around IP bans\" section of the README (https://github.com/jdepoix/youtube-transcript-api?tab=readme-ov-file#working-around-ip-bans-requestblocked-or-ipblocked-exception).\n",
      "2. (NOT RECOMMENDED) If you authenticate your requests using cookies, you will be able to continue doing requests for a while. However, YouTube will eventually permanently ban the account that you have used to authenticate with! So only do this if you don't mind your account being banned!\n",
      "\n",
      "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
      "2025-05-29 15:12:43 ERROR    ✖️  [https://youtu.be/DcvdOWitb3I] failed after 3 attempts\n",
      "2025-05-29 15:12:48 INFO     ✅ [https://youtu.be/ohuDHYE1ipQ] loaded on attempt 1\n",
      "2025-05-29 15:12:53 INFO     ✅ [https://youtu.be/Sz6E0KoNgoQ] loaded on attempt 1\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mKeyboardInterrupt\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 74\u001b[39m\n\u001b[32m     71\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m url \u001b[38;5;129;01min\u001b[39;00m processed_urls:\n\u001b[32m     72\u001b[39m     \u001b[38;5;28;01mcontinue\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m74\u001b[39m docs = load_with_retry(url)\n\u001b[32m     75\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m docs:\n\u001b[32m     76\u001b[39m     all_transcripts.extend(docs)\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 56\u001b[39m, in \u001b[36mload_with_retry\u001b[39m\u001b[34m(url)\u001b[39m\n\u001b[32m     52\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m attempt \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[32m1\u001b[39m, RETRIES + \u001b[32m1\u001b[39m):\n\u001b[32m     53\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m     54\u001b[39m         docs = YoutubeLoader.from_youtube_url(\n\u001b[32m     55\u001b[39m             url, add_video_info=\u001b[38;5;28;01mTrue\u001b[39;00m, translation=\u001b[33m\"\u001b[39m\u001b[33men\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m---> \u001b[39m\u001b[32m56\u001b[39m         ).load()\n\u001b[32m     57\u001b[39m         logging.info(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m✅ [\u001b[39m\u001b[38;5;132;01m{\u001b[39;00murl\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m] loaded on attempt \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mattempt\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m     58\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m docs\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/langchain_community/document_loaders/youtube.py:262\u001b[39m, in \u001b[36mYoutubeLoader.load\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    259\u001b[39m     \u001b[38;5;28mself\u001b[39m._metadata.update(video_info)\n\u001b[32m    261\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m262\u001b[39m     transcript_list = YouTubeTranscriptApi.list_transcripts(\u001b[38;5;28mself\u001b[39m.video_id)\n\u001b[32m    263\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m TranscriptsDisabled:\n\u001b[32m    264\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m []\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py:207\u001b[39m, in \u001b[36mYouTubeTranscriptApi.list_transcripts\u001b[39m\u001b[34m(cls, video_id, proxies, cookies)\u001b[39m\n\u001b[32m    199\u001b[39m         proxy_config = GenericProxyConfig(\n\u001b[32m    200\u001b[39m             http_url=proxies.get(\u001b[33m\"\u001b[39m\u001b[33mhttp\u001b[39m\u001b[33m\"\u001b[39m), https_url=proxies.get(\u001b[33m\"\u001b[39m\u001b[33mhttps\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    201\u001b[39m         )\n\u001b[32m    203\u001b[39m ytt_api = YouTubeTranscriptApi(\n\u001b[32m    204\u001b[39m     proxy_config=proxy_config,\n\u001b[32m    205\u001b[39m     cookie_path=Path(cookies) \u001b[38;5;28;01mif\u001b[39;00m cookies \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[32m    206\u001b[39m )\n\u001b[32m--> \u001b[39m\u001b[32m207\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m ytt_api.list(video_id)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_api.py:135\u001b[39m, in \u001b[36mYouTubeTranscriptApi.list\u001b[39m\u001b[34m(self, video_id)\u001b[39m\n\u001b[32m     84\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mlist\u001b[39m(\n\u001b[32m     85\u001b[39m     \u001b[38;5;28mself\u001b[39m,\n\u001b[32m     86\u001b[39m     video_id: \u001b[38;5;28mstr\u001b[39m,\n\u001b[32m     87\u001b[39m ) -> TranscriptList:\n\u001b[32m     88\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m     89\u001b[39m \u001b[33;03m    Retrieves the list of transcripts which are available for a given video. It\u001b[39;00m\n\u001b[32m     90\u001b[39m \u001b[33;03m    returns a `TranscriptList` object which is iterable and provides methods to\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    133\u001b[39m \u001b[33;03m        Make sure that this is the actual ID, NOT the full URL to the video!\u001b[39;00m\n\u001b[32m    134\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m135\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._fetcher.fetch(video_id)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py:352\u001b[39m, in \u001b[36mTranscriptListFetcher.fetch\u001b[39m\u001b[34m(self, video_id)\u001b[39m\n\u001b[32m    348\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mfetch\u001b[39m(\u001b[38;5;28mself\u001b[39m, video_id: \u001b[38;5;28mstr\u001b[39m) -> TranscriptList:\n\u001b[32m    349\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m TranscriptList.build(\n\u001b[32m    350\u001b[39m         \u001b[38;5;28mself\u001b[39m._http_client,\n\u001b[32m    351\u001b[39m         video_id,\n\u001b[32m--> \u001b[39m\u001b[32m352\u001b[39m         \u001b[38;5;28mself\u001b[39m._fetch_captions_json(video_id),\n\u001b[32m    353\u001b[39m     )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py:358\u001b[39m, in \u001b[36mTranscriptListFetcher._fetch_captions_json\u001b[39m\u001b[34m(self, video_id, try_number)\u001b[39m\n\u001b[32m    355\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_fetch_captions_json\u001b[39m(\u001b[38;5;28mself\u001b[39m, video_id: \u001b[38;5;28mstr\u001b[39m, try_number: \u001b[38;5;28mint\u001b[39m = \u001b[32m0\u001b[39m) -> Dict:\n\u001b[32m    356\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    357\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._extract_captions_json(\n\u001b[32m--> \u001b[39m\u001b[32m358\u001b[39m             \u001b[38;5;28mself\u001b[39m._fetch_video_html(video_id), video_id\n\u001b[32m    359\u001b[39m         )\n\u001b[32m    360\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m RequestBlocked \u001b[38;5;28;01mas\u001b[39;00m exception:\n\u001b[32m    361\u001b[39m         retries = (\n\u001b[32m    362\u001b[39m             \u001b[32m0\u001b[39m\n\u001b[32m    363\u001b[39m             \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._proxy_config \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    364\u001b[39m             \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28mself\u001b[39m._proxy_config.retries_when_blocked\n\u001b[32m    365\u001b[39m         )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py:428\u001b[39m, in \u001b[36mTranscriptListFetcher._fetch_video_html\u001b[39m\u001b[34m(self, video_id)\u001b[39m\n\u001b[32m    427\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_fetch_video_html\u001b[39m(\u001b[38;5;28mself\u001b[39m, video_id: \u001b[38;5;28mstr\u001b[39m) -> \u001b[38;5;28mstr\u001b[39m:\n\u001b[32m--> \u001b[39m\u001b[32m428\u001b[39m     html = \u001b[38;5;28mself\u001b[39m._fetch_html(video_id)\n\u001b[32m    429\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[33m'\u001b[39m\u001b[33maction=\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mhttps://consent.youtube.com/s\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m'\u001b[39m \u001b[38;5;129;01min\u001b[39;00m html:\n\u001b[32m    430\u001b[39m         \u001b[38;5;28mself\u001b[39m._create_consent_cookie(html, video_id)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/youtube_transcript_api/_transcripts.py:437\u001b[39m, in \u001b[36mTranscriptListFetcher._fetch_html\u001b[39m\u001b[34m(self, video_id)\u001b[39m\n\u001b[32m    436\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_fetch_html\u001b[39m(\u001b[38;5;28mself\u001b[39m, video_id: \u001b[38;5;28mstr\u001b[39m) -> \u001b[38;5;28mstr\u001b[39m:\n\u001b[32m--> \u001b[39m\u001b[32m437\u001b[39m     response = \u001b[38;5;28mself\u001b[39m._http_client.get(WATCH_URL.format(video_id=video_id))\n\u001b[32m    438\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m unescape(_raise_http_errors(response, video_id).text)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/requests/sessions.py:602\u001b[39m, in \u001b[36mSession.get\u001b[39m\u001b[34m(self, url, **kwargs)\u001b[39m\n\u001b[32m    594\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33mr\u001b[39m\u001b[33;03m\"\"\"Sends a GET request. Returns :class:`Response` object.\u001b[39;00m\n\u001b[32m    595\u001b[39m \n\u001b[32m    596\u001b[39m \u001b[33;03m:param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[32m    597\u001b[39m \u001b[33;03m:param \\*\\*kwargs: Optional arguments that ``request`` takes.\u001b[39;00m\n\u001b[32m    598\u001b[39m \u001b[33;03m:rtype: requests.Response\u001b[39;00m\n\u001b[32m    599\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m    601\u001b[39m kwargs.setdefault(\u001b[33m\"\u001b[39m\u001b[33mallow_redirects\u001b[39m\u001b[33m\"\u001b[39m, \u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[32m--> \u001b[39m\u001b[32m602\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m.request(\u001b[33m\"\u001b[39m\u001b[33mGET\u001b[39m\u001b[33m\"\u001b[39m, url, **kwargs)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/requests/sessions.py:589\u001b[39m, in \u001b[36mSession.request\u001b[39m\u001b[34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[39m\n\u001b[32m    584\u001b[39m send_kwargs = {\n\u001b[32m    585\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mtimeout\u001b[39m\u001b[33m\"\u001b[39m: timeout,\n\u001b[32m    586\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mallow_redirects\u001b[39m\u001b[33m\"\u001b[39m: allow_redirects,\n\u001b[32m    587\u001b[39m }\n\u001b[32m    588\u001b[39m send_kwargs.update(settings)\n\u001b[32m--> \u001b[39m\u001b[32m589\u001b[39m resp = \u001b[38;5;28mself\u001b[39m.send(prep, **send_kwargs)\n\u001b[32m    591\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m resp\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/requests/sessions.py:703\u001b[39m, in \u001b[36mSession.send\u001b[39m\u001b[34m(self, request, **kwargs)\u001b[39m\n\u001b[32m    700\u001b[39m start = preferred_clock()\n\u001b[32m    702\u001b[39m \u001b[38;5;66;03m# Send the request\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m703\u001b[39m r = adapter.send(request, **kwargs)\n\u001b[32m    705\u001b[39m \u001b[38;5;66;03m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[32m    706\u001b[39m elapsed = preferred_clock() - start\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/requests/adapters.py:667\u001b[39m, in \u001b[36mHTTPAdapter.send\u001b[39m\u001b[34m(self, request, stream, timeout, verify, cert, proxies)\u001b[39m\n\u001b[32m    664\u001b[39m     timeout = TimeoutSauce(connect=timeout, read=timeout)\n\u001b[32m    666\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m667\u001b[39m     resp = conn.urlopen(\n\u001b[32m    668\u001b[39m         method=request.method,\n\u001b[32m    669\u001b[39m         url=url,\n\u001b[32m    670\u001b[39m         body=request.body,\n\u001b[32m    671\u001b[39m         headers=request.headers,\n\u001b[32m    672\u001b[39m         redirect=\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[32m    673\u001b[39m         assert_same_host=\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[32m    674\u001b[39m         preload_content=\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[32m    675\u001b[39m         decode_content=\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[32m    676\u001b[39m         retries=\u001b[38;5;28mself\u001b[39m.max_retries,\n\u001b[32m    677\u001b[39m         timeout=timeout,\n\u001b[32m    678\u001b[39m         chunked=chunked,\n\u001b[32m    679\u001b[39m     )\n\u001b[32m    681\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (ProtocolError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    682\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m(err, request=request)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/urllib3/connectionpool.py:787\u001b[39m, in \u001b[36mHTTPConnectionPool.urlopen\u001b[39m\u001b[34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[39m\n\u001b[32m    784\u001b[39m response_conn = conn \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m release_conn \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    786\u001b[39m \u001b[38;5;66;03m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m787\u001b[39m response = \u001b[38;5;28mself\u001b[39m._make_request(\n\u001b[32m    788\u001b[39m     conn,\n\u001b[32m    789\u001b[39m     method,\n\u001b[32m    790\u001b[39m     url,\n\u001b[32m    791\u001b[39m     timeout=timeout_obj,\n\u001b[32m    792\u001b[39m     body=body,\n\u001b[32m    793\u001b[39m     headers=headers,\n\u001b[32m    794\u001b[39m     chunked=chunked,\n\u001b[32m    795\u001b[39m     retries=retries,\n\u001b[32m    796\u001b[39m     response_conn=response_conn,\n\u001b[32m    797\u001b[39m     preload_content=preload_content,\n\u001b[32m    798\u001b[39m     decode_content=decode_content,\n\u001b[32m    799\u001b[39m     **response_kw,\n\u001b[32m    800\u001b[39m )\n\u001b[32m    802\u001b[39m \u001b[38;5;66;03m# Everything went great!\u001b[39;00m\n\u001b[32m    803\u001b[39m clean_exit = \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/urllib3/connectionpool.py:534\u001b[39m, in \u001b[36mHTTPConnectionPool._make_request\u001b[39m\u001b[34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[39m\n\u001b[32m    532\u001b[39m \u001b[38;5;66;03m# Receive the response from the server\u001b[39;00m\n\u001b[32m    533\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m534\u001b[39m     response = conn.getresponse()\n\u001b[32m    535\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (BaseSSLError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    536\u001b[39m     \u001b[38;5;28mself\u001b[39m._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/site-packages/urllib3/connection.py:516\u001b[39m, in \u001b[36mHTTPConnection.getresponse\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    513\u001b[39m _shutdown = \u001b[38;5;28mgetattr\u001b[39m(\u001b[38;5;28mself\u001b[39m.sock, \u001b[33m\"\u001b[39m\u001b[33mshutdown\u001b[39m\u001b[33m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m    515\u001b[39m \u001b[38;5;66;03m# Get the response from http.client.HTTPConnection\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m516\u001b[39m httplib_response = \u001b[38;5;28msuper\u001b[39m().getresponse()\n\u001b[32m    518\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    519\u001b[39m     assert_header_parsing(httplib_response.msg)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/http/client.py:1430\u001b[39m, in \u001b[36mHTTPConnection.getresponse\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   1428\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m   1429\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m-> \u001b[39m\u001b[32m1430\u001b[39m         response.begin()\n\u001b[32m   1431\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m:\n\u001b[32m   1432\u001b[39m         \u001b[38;5;28mself\u001b[39m.close()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/http/client.py:331\u001b[39m, in \u001b[36mHTTPResponse.begin\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    329\u001b[39m \u001b[38;5;66;03m# read until we get a non-100 response\u001b[39;00m\n\u001b[32m    330\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m331\u001b[39m     version, status, reason = \u001b[38;5;28mself\u001b[39m._read_status()\n\u001b[32m    332\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m status != CONTINUE:\n\u001b[32m    333\u001b[39m         \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/http/client.py:292\u001b[39m, in \u001b[36mHTTPResponse._read_status\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    291\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_read_status\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[32m--> \u001b[39m\u001b[32m292\u001b[39m     line = \u001b[38;5;28mstr\u001b[39m(\u001b[38;5;28mself\u001b[39m.fp.readline(_MAXLINE + \u001b[32m1\u001b[39m), \u001b[33m\"\u001b[39m\u001b[33miso-8859-1\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    293\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(line) > _MAXLINE:\n\u001b[32m    294\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m LineTooLong(\u001b[33m\"\u001b[39m\u001b[33mstatus line\u001b[39m\u001b[33m\"\u001b[39m)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/socket.py:719\u001b[39m, in \u001b[36mSocketIO.readinto\u001b[39m\u001b[34m(self, b)\u001b[39m\n\u001b[32m    717\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mOSError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mcannot read from timed out object\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    718\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m719\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._sock.recv_into(b)\n\u001b[32m    720\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m timeout:\n\u001b[32m    721\u001b[39m     \u001b[38;5;28mself\u001b[39m._timeout_occurred = \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/ssl.py:1304\u001b[39m, in \u001b[36mSSLSocket.recv_into\u001b[39m\u001b[34m(self, buffer, nbytes, flags)\u001b[39m\n\u001b[32m   1300\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m flags != \u001b[32m0\u001b[39m:\n\u001b[32m   1301\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[32m   1302\u001b[39m           \u001b[33m\"\u001b[39m\u001b[33mnon-zero flags not allowed in calls to recv_into() on \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m\"\u001b[39m %\n\u001b[32m   1303\u001b[39m           \u001b[38;5;28mself\u001b[39m.\u001b[34m__class__\u001b[39m)\n\u001b[32m-> \u001b[39m\u001b[32m1304\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m.read(nbytes, buffer)\n\u001b[32m   1305\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m   1306\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28msuper\u001b[39m().recv_into(buffer, nbytes, flags)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/anaconda3/envs/video/lib/python3.13/ssl.py:1138\u001b[39m, in \u001b[36mSSLSocket.read\u001b[39m\u001b[34m(self, len, buffer)\u001b[39m\n\u001b[32m   1136\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m   1137\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m buffer \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m-> \u001b[39m\u001b[32m1138\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._sslobj.read(\u001b[38;5;28mlen\u001b[39m, buffer)\n\u001b[32m   1139\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m   1140\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._sslobj.read(\u001b[38;5;28mlen\u001b[39m)\n",
      "\u001b[31mKeyboardInterrupt\u001b[39m: "
     ]
    }
   ],
   "source": [
    "import os\n",
    "import time\n",
    "import random\n",
    "import logging\n",
    "import json\n",
    "from xml.parsers.expat import ExpatError\n",
    "from xml.etree.ElementTree import ParseError\n",
    "from langchain_community.document_loaders import YoutubeLoader\n",
    "from langchain.schema import Document   # for reconstructing\n",
    "\n",
    "RETRIES    = 3\n",
    "BASE_DELAY = 2.0\n",
    "STATE_FILE_1 = \"News_yt_state.json\"\n",
    "logging.basicConfig(\n",
    "    filename=None,\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s %(levelname)-8s %(message)s\",\n",
    "    datefmt = \"%Y-%m-%d %H:%M:%S\"\n",
    ")\n",
    "\n",
    "# ─── LOAD STATE ───────────────────────────────────────────────────────────\n",
    "if os.path.exists(STATE_FILE_1):\n",
    "    with open(STATE_FILE_1, \"r\", encoding=\"utf-8\") as f:\n",
    "        state = json.load(f)\n",
    "    all_transcripts = [\n",
    "        Document(page_content=d[\"page_content\"], metadata=d[\"metadata\"])\n",
    "        for d in state.get(\"all_transcripts\", [])\n",
    "    ]\n",
    "    not_working    = state.get(\"not_working\", [])\n",
    "    processed_urls = set(state.get(\"processed_urls\", []))\n",
    "    logging.info(f\"Resumed state: {len(all_transcripts)} docs, \"\n",
    "                 f\"{len(not_working)} failures, {len(processed_urls)} done\")\n",
    "else:\n",
    "    all_transcripts, not_working, processed_urls = [], [], set()\n",
    "\n",
    "def save_state():\n",
    "    payload = {\n",
    "        \"all_transcripts\": [\n",
    "            {\"page_content\": doc.page_content, \"metadata\": doc.metadata}\n",
    "            for doc in all_transcripts\n",
    "        ],\n",
    "        \"not_working\": list(not_working),\n",
    "        \"processed_urls\": list(processed_urls),\n",
    "    }\n",
    "    with open(STATE_FILE_1, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(payload, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "def load_with_retry(url):\n",
    "    for attempt in range(1, RETRIES + 1):\n",
    "        try:\n",
    "            docs = YoutubeLoader.from_youtube_url(\n",
    "                url, add_video_info=True, translation=\"en\"\n",
    "            ).load()\n",
    "            logging.info(f\"✅ [{url}] loaded on attempt {attempt}\")\n",
    "            return docs\n",
    "        except (ExpatError, ParseError) as e:\n",
    "            logging.warning(f\"⚠️  [{url}] parse error on attempt {attempt}: {e}\")\n",
    "        except Exception as e:\n",
    "            logging.error(f\"❌ [{url}] unexpected error: {e}\", exc_info=True)\n",
    "            break\n",
    "        backoff = BASE_DELAY * (2 ** (attempt - 1)) + random.random()\n",
    "        time.sleep(backoff)\n",
    "    logging.error(f\"✖️  [{url}] failed after {RETRIES} attempts\")\n",
    "    return []\n",
    "\n",
    "# ─── MAIN LOOP ────────────────────────────────────────────────────────────\n",
    "for url in News_urls:    \n",
    "    if url in processed_urls:\n",
    "        continue\n",
    "        \n",
    "    docs = load_with_retry(url)\n",
    "    if docs:\n",
    "        all_transcripts.extend(docs)\n",
    "    else:\n",
    "        not_working.append(url)\n",
    "    processed_urls.add(url)\n",
    "    save_state()        # ← write JSON after each URL\n",
    "    time.sleep(1.5)\n",
    "\n",
    "logging.info(f\"Done: {len(all_transcripts)} docs, {len(not_working)} failures\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1438c18",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import random\n",
    "import logging\n",
    "import json\n",
    "from xml.parsers.expat import ExpatError\n",
    "from xml.etree.ElementTree import ParseError\n",
    "from langchain_community.document_loaders import YoutubeLoader\n",
    "from langchain.schema import Document   # for reconstructing\n",
    "\n",
    "\n",
    "RETRIES    = 3\n",
    "BASE_DELAY = 2.0\n",
    "STATE_FILE_2 = \"Entartainment_yt_state.json\"\n",
    "logging.basicConfig(\n",
    "    filename=None,\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s %(levelname)-8s %(message)s\",\n",
    "    datefmt = \"%Y-%m-%d %H:%M:%S\"\n",
    ")\n",
    "\n",
    "# ─── LOAD STATE ───────────────────────────────────────────────────────────\n",
    "if os.path.exists(STATE_FILE_2):\n",
    "    with open(STATE_FILE_2, \"r\", encoding=\"utf-8\") as f:\n",
    "        state = json.load(f)\n",
    "    all_transcripts = [\n",
    "        Document(page_content=d[\"page_content\"], metadata=d[\"metadata\"])\n",
    "        for d in state.get(\"all_transcripts\", [])\n",
    "    ]\n",
    "    not_working    = state.get(\"not_working\", [])\n",
    "    processed_urls = set(state.get(\"processed_urls\", []))\n",
    "    logging.info(f\"Resumed state: {len(all_transcripts)} docs, \"\n",
    "                 f\"{len(not_working)} failures, {len(processed_urls)} done\")\n",
    "else:\n",
    "    all_transcripts, not_working, processed_urls = [], [], set()\n",
    "\n",
    "def save_state():\n",
    "    payload = {\n",
    "        \"all_transcripts\": [\n",
    "            {\"page_content\": doc.page_content, \"metadata\": doc.metadata}\n",
    "            for doc in all_transcripts\n",
    "        ],\n",
    "        \"not_working\": list(not_working),\n",
    "        \"processed_urls\": list(processed_urls),\n",
    "    }\n",
    "    with open(STATE_FILE_2, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(payload, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "def load_with_retry(url):\n",
    "    for attempt in range(1, RETRIES + 1):\n",
    "        try:\n",
    "            docs = YoutubeLoader.from_youtube_url(\n",
    "                url, add_video_info=True, translation=\"en\"\n",
    "            ).load()\n",
    "            logging.info(f\"✅ [{url}] loaded on attempt {attempt}\")\n",
    "            return docs\n",
    "        except (ExpatError, ParseError) as e:\n",
    "            logging.warning(f\"⚠️  [{url}] parse error on attempt {attempt}: {e}\")\n",
    "        except Exception as e:\n",
    "            logging.error(f\"❌ [{url}] unexpected error: {e}\", exc_info=True)\n",
    "            break\n",
    "        backoff = BASE_DELAY * (2 ** (attempt - 1)) + random.random()\n",
    "        time.sleep(backoff)\n",
    "    logging.error(f\"✖️  [{url}] failed after {RETRIES} attempts\")\n",
    "    return []\n",
    "\n",
    "# ─── MAIN LOOP ────────────────────────────────────────────────────────────\n",
    "for url in Entertainment_urls:    \n",
    "    if url in processed_urls:\n",
    "        continue\n",
    "        \n",
    "    docs = load_with_retry(url)\n",
    "    if docs:\n",
    "        all_transcripts.extend(docs)\n",
    "    else:\n",
    "        not_working.append(url)\n",
    "    processed_urls.add(url)\n",
    "    save_state()        # ← write JSON after each URL\n",
    "    time.sleep(1.5)\n",
    "\n",
    "logging.info(f\"Done: {len(all_transcripts)} docs, {len(not_working)} failures\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4c483204",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%px --targets 2\n",
    "\n",
    "import os\n",
    "import time\n",
    "import random\n",
    "import logging\n",
    "import json\n",
    "from xml.parsers.expat import ExpatError\n",
    "from xml.etree.ElementTree import ParseError\n",
    "from langchain_community.document_loaders import YoutubeLoader\n",
    "from langchain.schema import Document   # for reconstructing\n",
    "\n",
    "\n",
    "RETRIES    = 3\n",
    "BASE_DELAY = 2.0\n",
    "STATE_FILE_3 = \"UK_Shows_yt_state.json\"\n",
    "logging.basicConfig(\n",
    "    filename=None,\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s %(levelname)-8s %(message)s\",\n",
    "    datefmt = \"%Y-%m-%d %H:%M:%S\"\n",
    ")\n",
    "\n",
    "# ─── LOAD STATE ───────────────────────────────────────────────────────────\n",
    "if os.path.exists(STATE_FILE_3):\n",
    "    with open(STATE_FILE_3, \"r\", encoding=\"utf-8\") as f:\n",
    "        state = json.load(f)\n",
    "    all_transcripts = [\n",
    "        Document(page_content=d[\"page_content\"], metadata=d[\"metadata\"])\n",
    "        for d in state.get(\"all_transcripts\", [])\n",
    "    ]\n",
    "    not_working    = state.get(\"not_working\", [])\n",
    "    processed_urls = set(state.get(\"processed_urls\", []))\n",
    "    logging.info(f\"Resumed state: {len(all_transcripts)} docs, \"\n",
    "                 f\"{len(not_working)} failures, {len(processed_urls)} done\")\n",
    "else:\n",
    "    all_transcripts, not_working, processed_urls = [], [], set()\n",
    "\n",
    "def save_state():\n",
    "    payload = {\n",
    "        \"all_transcripts\": [\n",
    "            {\"page_content\": doc.page_content, \"metadata\": doc.metadata}\n",
    "            for doc in all_transcripts\n",
    "        ],\n",
    "        \"not_working\": list(not_working),\n",
    "        \"processed_urls\": list(processed_urls),\n",
    "    }\n",
    "    with open(STATE_FILE_3, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(payload, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "def load_with_retry(url):\n",
    "    for attempt in range(1, RETRIES + 1):\n",
    "        try:\n",
    "            docs = YoutubeLoader.from_youtube_url(\n",
    "                url, add_video_info=True, translation=\"en\"\n",
    "            ).load()\n",
    "            logging.info(f\"✅ [{url}] loaded on attempt {attempt}\")\n",
    "            return docs\n",
    "        except (ExpatError, ParseError) as e:\n",
    "            logging.warning(f\"⚠️  [{url}] parse error on attempt {attempt}: {e}\")\n",
    "        except Exception as e:\n",
    "            logging.error(f\"❌ [{url}] unexpected error: {e}\", exc_info=True)\n",
    "            break\n",
    "        backoff = BASE_DELAY * (2 ** (attempt - 1)) + random.random()\n",
    "        time.sleep(backoff)\n",
    "    logging.error(f\"✖️  [{url}] failed after {RETRIES} attempts\")\n",
    "    return []\n",
    "\n",
    "# ─── MAIN LOOP ────────────────────────────────────────────────────────────\n",
    "for url in UK_urls:    \n",
    "    if url in processed_urls:\n",
    "        continue\n",
    "        \n",
    "    docs = load_with_retry(url)\n",
    "    if docs:\n",
    "        all_transcripts.extend(docs)\n",
    "    else:\n",
    "        not_working.append(url)\n",
    "    processed_urls.add(url)\n",
    "    save_state()        # ← write JSON after each URL\n",
    "    time.sleep(1.5)\n",
    "\n",
    "logging.info(f\"Done: {len(all_transcripts)} docs, {len(not_working)} failures\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c1d4ec2c",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%px --targets 3\n",
    "\n",
    "import os\n",
    "import time\n",
    "time.sleep(4)\n",
    "import random\n",
    "import logging\n",
    "import json\n",
    "from xml.parsers.expat import ExpatError\n",
    "from xml.etree.ElementTree import ParseError\n",
    "from langchain_community.document_loaders import YoutubeLoader\n",
    "from langchain.schema import Document   # for reconstructing\n",
    "\n",
    "RETRIES    = 3\n",
    "BASE_DELAY = 2.0\n",
    "STATE_FILE_4 = \"US_Shows_yt_state.json\"\n",
    "logging.basicConfig(\n",
    "    filename=None,\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s %(levelname)-8s %(message)s\",\n",
    "    datefmt = \"%Y-%m-%d %H:%M:%S\"\n",
    ")\n",
    "\n",
    "# ─── LOAD STATE ───────────────────────────────────────────────────────────\n",
    "if os.path.exists(STATE_FILE_4):\n",
    "    with open(STATE_FILE_4, \"r\", encoding=\"utf-8\") as f:\n",
    "        state = json.load(f)\n",
    "    all_transcripts = [\n",
    "        Document(page_content=d[\"page_content\"], metadata=d[\"metadata\"])\n",
    "        for d in state.get(\"all_transcripts\", [])\n",
    "    ]\n",
    "    not_working    = state.get(\"not_working\", [])\n",
    "    processed_urls = set(state.get(\"processed_urls\", []))\n",
    "    logging.info(f\"Resumed state: {len(all_transcripts)} docs, \"\n",
    "                 f\"{len(not_working)} failures, {len(processed_urls)} done\")\n",
    "else:\n",
    "    all_transcripts, not_working, processed_urls = [], [], set()\n",
    "\n",
    "def save_state():\n",
    "    payload = {\n",
    "        \"all_transcripts\": [\n",
    "            {\"page_content\": doc.page_content, \"metadata\": doc.metadata}\n",
    "            for doc in all_transcripts\n",
    "        ],\n",
    "        \"not_working\": list(not_working),\n",
    "        \"processed_urls\": list(processed_urls),\n",
    "    }\n",
    "    with open(STATE_FILE_4, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(payload, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "def load_with_retry(url):\n",
    "    for attempt in range(1, RETRIES + 1):\n",
    "        try:\n",
    "            docs = YoutubeLoader.from_youtube_url(\n",
    "                url, add_video_info=True, translation=\"en\"\n",
    "            ).load()\n",
    "            logging.info(f\"✅ [{url}] loaded on attempt {attempt}\")\n",
    "            return docs\n",
    "        except (ExpatError, ParseError) as e:\n",
    "            logging.warning(f\"⚠️  [{url}] parse error on attempt {attempt}: {e}\")\n",
    "        except Exception as e:\n",
    "            logging.error(f\"❌ [{url}] unexpected error: {e}\", exc_info=True)\n",
    "            break\n",
    "        backoff = BASE_DELAY * (2 ** (attempt - 1)) + random.random()\n",
    "        time.sleep(backoff)\n",
    "    logging.error(f\"✖️  [{url}] failed after {RETRIES} attempts\")\n",
    "    return []\n",
    "\n",
    "# ─── MAIN LOOP ────────────────────────────────────────────────────────────\n",
    "for url in US_urls:    \n",
    "    if url in processed_urls:\n",
    "        continue\n",
    "        \n",
    "    docs = load_with_retry(url)\n",
    "    if docs:\n",
    "        all_transcripts.extend(docs)\n",
    "    else:\n",
    "        not_working.append(url)\n",
    "    processed_urls.add(url)\n",
    "    save_state()        # ← write JSON after each URL\n",
    "    time.sleep(1.5)\n",
    "\n",
    "logging.info(f\"Done: {len(all_transcripts)} docs, {len(not_working)} failures\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2ad2d415",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "videoKernel",
   "language": "python",
   "name": "videokernel"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
